version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./web/:/var/www/web/
        ports:
            - 8001:80
        networks:
            - webNet
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@mysql:3306/laravel_cms_db?serverVersion=5.7
        volumes:
            - ./web/:/var/www/web/
        networks:
            - webNet
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: laravel_cms_db
            MYSQL_PASSWORD: example
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - webNet
networks:
    webNet: